load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "view",
    srcs = [
        "canvas_controls.cpp",
        "editor_view.cpp",
    ],
    hdrs = [
        "canvas_controls.hpp",
        "editor_view.hpp",
    ],
    target_compatible_with = select({
        "//config:wasm": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//canvas",
        "//canvas:http_texture_provider",
        "//model",
        "//third_party/egb_imgui:icons",
        "//third_party/egb_imgui:widgets",
        "@imgui_docking//:imgui",
        "@imgui_docking//:imgui_stdlib",
    ],
)
